// What the working row says the turn is doing. One is picked per turn and held
// for the whole turn: a verb that changed every few seconds would read as noise,
// and the point of the line is that something is happening, not what.
//
// Short, lower-case, mostly the ordinary work of a coding agent, with enough dry
// humour in the list that a long turn is worth watching.
export const VERBS = [
  'thinking',
  'planning',
  'reading the source',
  'reading the diff',
  'reading the stack trace',
  'reading the changelog',
  'reading the man page',
  'reading the lockfile',
  'grepping',
  'walking the tree',
  'mapping the call graph',
  'following the trail',
  'chasing pointers',
  'unwinding the stack',
  'squinting at logs',
  'bisecting',
  'reproducing',
  'narrowing it down',
  'isolating the failure',
  'instrumenting',
  'profiling',
  'benchmarking',
  'timing it',
  'hunting the leak',
  'chasing a race',
  'refactoring',
  'extracting a function',
  'inlining',
  'renaming',
  'naming things',
  'simplifying',
  'deleting code',
  'deleting more code',
  'tidying',
  'formatting',
  'sorting imports',
  'linting',
  'appeasing the linter',
  'type-checking',
  'narrowing unions',
  'inferring generics',
  'fixing the types',
  'compiling',
  'transpiling',
  'bundling',
  'resolving imports',
  'writing tests',
  'running tests',
  'watching tests fail',
  'fixing the tests',
  'mocking things out',
  'stubbing',
  'asserting',
  'diffing',
  'patching',
  'staging hunks',
  'committing',
  'amending',
  'rebasing',
  'resolving conflicts',
  'cherry-picking',
  'blaming git',
  'reverting',
  'opening the PR',
  'reviewing',
  'leaving nits',
  'addressing feedback',
  'squashing',
  'waiting on CI',
  'rereading CI logs',
  'herding goroutines',
  'awaiting promises',
  'joining threads',
  'taking the lock',
  'dropping the lock',
  'draining the queue',
  'batching',
  'streaming',
  'buffering',
  'flushing',
  'backing off',
  'retrying',
  'handling the error',
  'validating input',
  'sanitising paths',
  'normalising',
  'escaping quotes',
  'counting parentheses',
  'balancing brackets',
  'arguing with yaml',
  'quoting the shell',
  'warming caches',
  'invalidating caches',
  'memoising',
  'indexing',
  'deduplicating',
  'migrating',
  'seeding',
  'rolling back',
  'reconciling',
  'wiring it up',
  'scaffolding',
  'generating',
  'templating',
  'bumping deps',
  'auditing deps',
  'pinning a version',
  'packaging',
  'writing the comment',
  'deleting the comment',
  'updating the README',
  'checking the spec',
  'checking the docs',
  'rubberducking',
  'bikeshedding',
  'shaving yaks',
  'second-guessing',
  'overthinking it',
  'undoing that',
  'doing it properly',
  'questioning the premise',
  'staring at it',
  'brewing coffee'
] as const
